# Stage 1: Build
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
# Kopiere alles außer den dist Ordner
COPY . .
RUN rm -rf dist
RUN npm run build -- --configuration production

# Stage 2: Serve
FROM nginx:alpine

# Umgebungsvariablen deklarieren
ENV API_BASE_URL=http://localhost:3000
ENV PRODUCTION=false

COPY --from=build /app/dist/recipes-app/browser /usr/share/nginx/html
COPY docker/resources/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/resources/config.template.json /config.template.json

# Entrypoint Skript kopieren und ausführbar machen
COPY docker/resources/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
